"""Add soft delete to categories

Revision ID: 68ea95b279b0
Revises: bcc0f3272e65
Create Date: 2026-08-14 02:49:57.726846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ea95b279b0'
down_revision: Union[str, Sequence[str], None] = 'bcc0f3272e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
