"""Add categories and update transactions

Revision ID: 81c55b084605
Revises: 9c192e87595b
Create Date: 2026-08-13 20:10:46.639872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c55b084605'
down_revision: Union[str, Sequence[str], None] = '9c192e87595b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    
    categories_table = sa.table(
        'categories',
        sa.Column('id', sa.UUID()),
        sa.Column('user_id', sa.UUID()),
        sa.Column('name', sa.String(length=50)),
        sa.Column('icon', sa.String(length=10)),
        sa.Column('color', sa.String(length=7)),
        sa.Column('type', sa.String(length=10)),
        sa.Column('is_default', sa.Boolean()),
        sa.Column('created_at', sa.DateTime(timezone=True))
    )
    import uuid
    from datetime import datetime, timezone
    
    op.bulk_insert(
        categories_table,
        [
            {"id": uuid.uuid4(), "user_id": None, "name": "Food & Dining", "icon": "🍔", "color": "#EF4444", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Shopping", "icon": "🛍️", "color": "#F59E0B", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Transport", "icon": "🚗", "color": "#3B82F6", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Bills & Utilities", "icon": "⚡", "color": "#8B5CF6", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Entertainment", "icon": "🎬", "color": "#EC4899", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Salary", "icon": "💰", "color": "#10B981", "type": "income", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Investments", "icon": "📈", "color": "#14B8A6", "type": "income", "is_default": True, "created_at": datetime.now(timezone.utc)},
            {"id": uuid.uuid4(), "user_id": None, "name": "Other", "icon": "📦", "color": "#6B7280", "type": "expense", "is_default": True, "created_at": datetime.now(timezone.utc)},
        ]
    )

    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('category_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('type', sa.String(length=10), nullable=False))
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('transactions', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('transactions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'tags')
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'user_id')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
